# Generated by Django 3.0.6 on 2020-05-21 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='app',
            name='content2',
        ),
        migrations.RemoveField(
            model_name='app',
            name='content3',
        ),
    ]
